package de.jpx3.intave.reflect.hitbox.typeaccess;

import de.jpx3.intave.reflect.hitbox.HitBoxBoundaries;

import java.util.HashMap;
import java.util.Map;

public final class DualEntityTypeAccess {
  private final static Map<Integer, HitBoxBoundaries> entityHitBoxMap = new HashMap<>();
  private final static Map<Integer, String> entityNameMap = new HashMap<>();

  static {
    loadHitBoxes();
    loadEntityNames();
  }

  private static void loadHitBoxes() {
    entityHitBoxMap.put(1, HitBoxBoundaries.of(0.5f, 1.975f));
    entityHitBoxMap.put(2, HitBoxBoundaries.of(0.5f, 0.5f));
    entityHitBoxMap.put(3, HitBoxBoundaries.of(0.5f, 0.9f));
    entityHitBoxMap.put(4, HitBoxBoundaries.of(0.7f, 0.6f));
    entityHitBoxMap.put(5, HitBoxBoundaries.of(0.6f, 1.8f));
    entityHitBoxMap.put(6, HitBoxBoundaries.of(1.375f, 0.5625f));
    entityHitBoxMap.put(7, HitBoxBoundaries.of(0.6f, 0.7f));
    entityHitBoxMap.put(8, HitBoxBoundaries.of(0.7f, 0.5f));
    entityHitBoxMap.put(9, HitBoxBoundaries.of(0.4f, 0.7f));
    entityHitBoxMap.put(10, HitBoxBoundaries.of(0.5f, 0.3f));
    entityHitBoxMap.put(11, HitBoxBoundaries.of(0.9f, 1.4f));
    entityHitBoxMap.put(12, HitBoxBoundaries.of(0.6f, 1.7f));
    entityHitBoxMap.put(13, HitBoxBoundaries.of(0.9f, 0.6f));
    entityHitBoxMap.put(14, HitBoxBoundaries.of(1.3964844f, 1.5f));
    entityHitBoxMap.put(15, HitBoxBoundaries.of(1.0f, 1.0f));
    entityHitBoxMap.put(16, HitBoxBoundaries.of(0.6f, 1.95f));
    entityHitBoxMap.put(17, HitBoxBoundaries.of(1.9975f, 1.9975f));
    entityHitBoxMap.put(18, HitBoxBoundaries.of(2.0f, 2.0f));
    entityHitBoxMap.put(19, HitBoxBoundaries.of(16.0f, 8.0f));
    entityHitBoxMap.put(20, HitBoxBoundaries.of(0.6f, 2.9f));
    entityHitBoxMap.put(21, HitBoxBoundaries.of(0.4f, 0.3f));
    entityHitBoxMap.put(22, HitBoxBoundaries.of(0.6f, 1.95f));
    entityHitBoxMap.put(23, HitBoxBoundaries.of(0.5f, 0.8f));
    entityHitBoxMap.put(24, HitBoxBoundaries.of(0.5f, 0.5f));
    entityHitBoxMap.put(25, HitBoxBoundaries.of(0.25f, 0.25f));
    entityHitBoxMap.put(26, HitBoxBoundaries.of(0.98f, 0.98f));
    entityHitBoxMap.put(27, HitBoxBoundaries.of(0.25f, 0.25f));
    entityHitBoxMap.put(28, HitBoxBoundaries.of(0.6f, 0.7f));
    entityHitBoxMap.put(29, HitBoxBoundaries.of(4.0f, 4.0f));
    entityHitBoxMap.put(30, HitBoxBoundaries.of(3.6f, 12.0f));
    entityHitBoxMap.put(31, HitBoxBoundaries.of(0.85f, 0.85f));
    entityHitBoxMap.put(32, HitBoxBoundaries.of(1.3964844f, 1.4f));
    entityHitBoxMap.put(33, HitBoxBoundaries.of(1.3964844f, 1.6f));
    entityHitBoxMap.put(34, HitBoxBoundaries.of(0.6f, 1.95f));
    entityHitBoxMap.put(35, HitBoxBoundaries.of(0.6f, 1.95f));
    entityHitBoxMap.put(36, HitBoxBoundaries.of(1.4f, 2.7f));
    entityHitBoxMap.put(37, HitBoxBoundaries.of(0.25f, 0.25f));
    entityHitBoxMap.put(38, HitBoxBoundaries.of(0.5f, 0.5f));
    entityHitBoxMap.put(39, HitBoxBoundaries.of(1.0f, 1.0f));
    entityHitBoxMap.put(40, HitBoxBoundaries.of(0.5f, 0.5f));
    entityHitBoxMap.put(41, HitBoxBoundaries.of(0.0f, 0.0f));
    entityHitBoxMap.put(42, HitBoxBoundaries.of(0.9f, 1.87f));
    entityHitBoxMap.put(43, HitBoxBoundaries.of(0.25f, 0.25f));
    entityHitBoxMap.put(44, HitBoxBoundaries.of(2.04f, 2.04f));
    entityHitBoxMap.put(45, HitBoxBoundaries.of(0.98f, 0.7f));
    entityHitBoxMap.put(46, HitBoxBoundaries.of(0.98f, 0.7f));
    entityHitBoxMap.put(47, HitBoxBoundaries.of(0.98f, 0.7f));
    entityHitBoxMap.put(48, HitBoxBoundaries.of(0.98f, 0.7f));
    entityHitBoxMap.put(49, HitBoxBoundaries.of(0.98f, 0.7f));
    entityHitBoxMap.put(50, HitBoxBoundaries.of(0.98f, 0.7f));
    entityHitBoxMap.put(51, HitBoxBoundaries.of(0.98f, 0.7f));
    entityHitBoxMap.put(52, HitBoxBoundaries.of(1.3964844f, 1.6f));
    entityHitBoxMap.put(53, HitBoxBoundaries.of(0.9f, 1.4f));
    entityHitBoxMap.put(54, HitBoxBoundaries.of(0.6f, 0.7f));
    entityHitBoxMap.put(55, HitBoxBoundaries.of(0.5f, 0.5f));
    entityHitBoxMap.put(56, HitBoxBoundaries.of(1.3f, 1.25f));
    entityHitBoxMap.put(57, HitBoxBoundaries.of(0.5f, 0.9f));
    entityHitBoxMap.put(58, HitBoxBoundaries.of(0.9f, 0.5f));
    entityHitBoxMap.put(59, HitBoxBoundaries.of(0.9f, 0.9f));
    entityHitBoxMap.put(60, HitBoxBoundaries.of(0.6f, 1.95f));
    entityHitBoxMap.put(61, HitBoxBoundaries.of(0.6f, 1.95f));
    entityHitBoxMap.put(62, HitBoxBoundaries.of(1.4f, 1.4f));
    entityHitBoxMap.put(63, HitBoxBoundaries.of(0.98f, 0.98f));
    entityHitBoxMap.put(64, HitBoxBoundaries.of(0.7f, 0.7f));
    entityHitBoxMap.put(65, HitBoxBoundaries.of(0.4f, 0.5f));
    entityHitBoxMap.put(66, HitBoxBoundaries.of(1.95f, 2.2f));
    entityHitBoxMap.put(67, HitBoxBoundaries.of(0.7f, 0.4f));
    entityHitBoxMap.put(68, HitBoxBoundaries.of(0.9f, 1.3f));
    entityHitBoxMap.put(69, HitBoxBoundaries.of(1.0f, 1.0f));
    entityHitBoxMap.put(70, HitBoxBoundaries.of(0.3125f, 0.3125f));
    entityHitBoxMap.put(71, HitBoxBoundaries.of(0.4f, 0.3f));
    entityHitBoxMap.put(72, HitBoxBoundaries.of(0.6f, 1.99f));
    entityHitBoxMap.put(73, HitBoxBoundaries.of(1.3964844f, 1.6f));
    entityHitBoxMap.put(74, HitBoxBoundaries.of(2.04f, 2.04f));
    entityHitBoxMap.put(75, HitBoxBoundaries.of(0.3125f, 0.3125f));
    entityHitBoxMap.put(76, HitBoxBoundaries.of(0.7f, 1.9f));
    entityHitBoxMap.put(77, HitBoxBoundaries.of(0.25f, 0.25f));
    entityHitBoxMap.put(78, HitBoxBoundaries.of(0.5f, 0.5f));
    entityHitBoxMap.put(79, HitBoxBoundaries.of(1.4f, 0.9f));
    entityHitBoxMap.put(80, HitBoxBoundaries.of(0.8f, 0.8f));
    entityHitBoxMap.put(81, HitBoxBoundaries.of(0.6f, 1.99f));
    entityHitBoxMap.put(82, HitBoxBoundaries.of(0.9f, 1.7f));
    entityHitBoxMap.put(83, HitBoxBoundaries.of(0.25f, 0.25f));
    entityHitBoxMap.put(84, HitBoxBoundaries.of(0.25f, 0.25f));
    entityHitBoxMap.put(85, HitBoxBoundaries.of(0.25f, 0.25f));
    entityHitBoxMap.put(86, HitBoxBoundaries.of(0.25f, 0.25f));
    entityHitBoxMap.put(87, HitBoxBoundaries.of(0.5f, 0.5f));
    entityHitBoxMap.put(88, HitBoxBoundaries.of(0.9f, 1.87f));
    entityHitBoxMap.put(89, HitBoxBoundaries.of(0.5f, 0.4f));
    entityHitBoxMap.put(90, HitBoxBoundaries.of(1.2f, 0.4f));
    entityHitBoxMap.put(91, HitBoxBoundaries.of(0.4f, 0.8f));
    entityHitBoxMap.put(92, HitBoxBoundaries.of(0.6f, 1.95f));
    entityHitBoxMap.put(93, HitBoxBoundaries.of(0.6f, 1.95f));
    entityHitBoxMap.put(94, HitBoxBoundaries.of(0.6f, 1.95f));
    entityHitBoxMap.put(95, HitBoxBoundaries.of(0.6f, 1.95f));
    entityHitBoxMap.put(96, HitBoxBoundaries.of(0.9f, 3.5f));
    entityHitBoxMap.put(97, HitBoxBoundaries.of(0.7f, 2.4f));
    entityHitBoxMap.put(98, HitBoxBoundaries.of(0.3125f, 0.3125f));
    entityHitBoxMap.put(99, HitBoxBoundaries.of(0.6f, 0.85f));
    entityHitBoxMap.put(100, HitBoxBoundaries.of(1.3964844f, 1.4f));
    entityHitBoxMap.put(101, HitBoxBoundaries.of(0.6f, 1.95f));
    entityHitBoxMap.put(102, HitBoxBoundaries.of(1.3964844f, 1.6f));
    entityHitBoxMap.put(103, HitBoxBoundaries.of(0.6f, 1.95f));
    entityHitBoxMap.put(104, HitBoxBoundaries.of(0.6f, 1.95f));
    entityHitBoxMap.put(105, HitBoxBoundaries.of(0.6f, 1.8f));
    entityHitBoxMap.put(106, HitBoxBoundaries.of(0.25f, 0.25f));
    entityHitBoxMap.put(107, HitBoxBoundaries.of(0.9f, 0.9f));
  }

  private static void loadEntityNames() {
    entityNameMap.put(1, "Armor Stand");
    entityNameMap.put(2, "Arrow");
    entityNameMap.put(3, "Bat");
    entityNameMap.put(4, "Bee");
    entityNameMap.put(5, "Blaze");
    entityNameMap.put(6, "Boat");
    entityNameMap.put(7, "Cat");
    entityNameMap.put(8, "Cave Spider");
    entityNameMap.put(9, "Chicken");
    entityNameMap.put(10, "Cod");
    entityNameMap.put(11, "Cow");
    entityNameMap.put(12, "Creeper");
    entityNameMap.put(13, "Dolphin");
    entityNameMap.put(14, "Donkey");
    entityNameMap.put(15, "Dragon Fireball");
    entityNameMap.put(16, "Drowned");
    entityNameMap.put(17, "Elder Guardian");
    entityNameMap.put(18, "End Crystal");
    entityNameMap.put(19, "Ender Dragon");
    entityNameMap.put(20, "Enderman");
    entityNameMap.put(21, "Endermite");
    entityNameMap.put(22, "Evoker");
    entityNameMap.put(23, "Evoker Fangs");
    entityNameMap.put(24, "Experience Orb");
    entityNameMap.put(25, "Eye of Ender");
    entityNameMap.put(26, "Falling Block");
    entityNameMap.put(27, "Firework Rocket");
    entityNameMap.put(28, "Fox");
    entityNameMap.put(29, "Ghast");
    entityNameMap.put(30, "Giant");
    entityNameMap.put(31, "Guardian");
    entityNameMap.put(32, "Hoglin");
    entityNameMap.put(33, "Horse");
    entityNameMap.put(34, "Husk");
    entityNameMap.put(35, "Illusioner");
    entityNameMap.put(36, "Iron Golem");
    entityNameMap.put(37, "Item");
    entityNameMap.put(38, "Item Frame");
    entityNameMap.put(39, "Fireball");
    entityNameMap.put(40, "Leash Knot");
    entityNameMap.put(41, "Lightning Bolt");
    entityNameMap.put(42, "Llama");
    entityNameMap.put(43, "Llama Spit");
    entityNameMap.put(44, "Magma Cube");
    entityNameMap.put(45, "Minecart");
    entityNameMap.put(46, "Minecart with Chest");
    entityNameMap.put(47, "Minecart with Command Block");
    entityNameMap.put(48, "Minecart with Furnace");
    entityNameMap.put(49, "Minecart with Hopper");
    entityNameMap.put(50, "Minecart with Spawner");
    entityNameMap.put(51, "Minecart with TNT");
    entityNameMap.put(52, "Mule");
    entityNameMap.put(53, "Mooshroom");
    entityNameMap.put(54, "Ocelot");
    entityNameMap.put(55, "Painting");
    entityNameMap.put(56, "Panda");
    entityNameMap.put(57, "Parrot");
    entityNameMap.put(58, "Phantom");
    entityNameMap.put(59, "Pig");
    entityNameMap.put(60, "Piglin");
    entityNameMap.put(61, "Pillager");
    entityNameMap.put(62, "Polar Bear");
    entityNameMap.put(63, "Primed TNT");
    entityNameMap.put(64, "Pufferfish");
    entityNameMap.put(65, "Rabbit");
    entityNameMap.put(66, "Ravager");
    entityNameMap.put(67, "Salmon");
    entityNameMap.put(68, "Sheep");
    entityNameMap.put(69, "Shulker");
    entityNameMap.put(70, "Shulker Bullet");
    entityNameMap.put(71, "Silverfish");
    entityNameMap.put(72, "Skeleton");
    entityNameMap.put(73, "Skeleton Horse");
    entityNameMap.put(74, "Slime");
    entityNameMap.put(75, "Small Fireball");
    entityNameMap.put(76, "Snow Golem");
    entityNameMap.put(77, "Snowball");
    entityNameMap.put(78, "Spectral Arrow");
    entityNameMap.put(79, "Spider");
    entityNameMap.put(80, "Squid");
    entityNameMap.put(81, "Stray");
    entityNameMap.put(82, "Strider");
    entityNameMap.put(83, "Thrown Egg");
    entityNameMap.put(84, "Thrown Ender Pearl");
    entityNameMap.put(85, "Thrown Bottle o' Enchanting");
    entityNameMap.put(86, "Potion");
    entityNameMap.put(87, "Trident");
    entityNameMap.put(88, "Trader Llama");
    entityNameMap.put(89, "Tropical Fish");
    entityNameMap.put(90, "Turtle");
    entityNameMap.put(91, "Vex");
    entityNameMap.put(92, "Villager");
    entityNameMap.put(93, "Vindicator");
    entityNameMap.put(94, "Wandering Trader");
    entityNameMap.put(95, "Witch");
    entityNameMap.put(96, "Wither");
    entityNameMap.put(97, "Wither Skeleton");
    entityNameMap.put(98, "Wither Skull");
    entityNameMap.put(99, "Wolf");
    entityNameMap.put(100, "Zoglin");
    entityNameMap.put(101, "Zombie");
    entityNameMap.put(102, "Zombie Horse");
    entityNameMap.put(103, "Zombie Villager");
    entityNameMap.put(104, "Zombified Piglin");
    entityNameMap.put(105, "Player");
    entityNameMap.put(106, "Fishing Bobber");
    entityNameMap.put(107, "Pig");
  }

  public static EntityTypeData resolveFromId(int entityTypeId) {
    return new EntityTypeData(nameFromID(entityTypeId), boundariesFromId(entityTypeId), entityTypeId);
  }

  public static HitBoxBoundaries boundariesFromId(int id) {
    return entityHitBoxMap.get(id);
  }

  public static String nameFromID(int id) {
    return entityNameMap.get(id);
  }
}